menu:
- {name: 'About', url: '/index#about'}
- {name: 'Posts', url: '/posts'}
#- {name: 'publications', url: '/publications'}
#- {name: 'courses', url: '/courses'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}

people:
- {name: 'Sam Goree', title: 'Graduate Research Fellow', department: 'Informatics', institution: 'Indiana University'}
#- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
#- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

#courses:
#- {name: 'Vector Calculus', url: 'vector-calculus'}
#- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
#- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/samgoree'}
- {icon: 'twitter', link: 'https://twitter.com/sam__goree'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/samuel-goree-38214471'}

contacts:
- {name: 'Sam Goree', title: 'Graduate Research Fellow', department: 'Department of Informatics, Luddy School of Informatics, Computing and Engineering', institution: 'Indiana University', email: 'sgoree [at] iu.edu'}
